# Generated by Django 4.1.1 on 2022-09-14 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=255)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=64)),
                ('descricao', models.TextField(max_length=128)),
                ('ativo', models.BooleanField(default=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('contato_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contato', to='todo.contato')),
            ],
        ),
    ]
