# Generated by Django 4.1.1 on 2022-09-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
