# Generated by Django 4.1.1 on 2022-09-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_tarefa_contato_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='data_cadastro',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_cadastro',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
