# Generated by Django 4.1.1 on 2022-09-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_contato_data_alteracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_cadastro',
            field=models.DateTimeField(auto_created=True, editable=False),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_cadastro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
